id: A99C16412
base_file: f2E7A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:35:02.801520
  last_modified_at: 2022-05-31 06:35:02.801556
