id: A99C16412
base_file: fC826.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:35:02.804737
  last_modified_at: 2022-05-31 06:35:02.804742
